apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: {{ .Release.Namespace }}
data:
  odoo.conf: |
    [options]
    db_host = postgres-master
    db_port = 5432
    db_user = odoo
    db_name = testing
    addons_path = /mnt/extra-addons
    admin_passwd = master

    server_wide_modules=web,base,wk_redis_session
    redis_session=True
    redis_host=redis
    redis_port=6379

    gevent_port = 8072
    data_dir = /var/lib/odoo
    proxy_mode = True
    workers = 8
    max_cron_threads = 2
    limit_memory_soft = 2048000000
    limit_memory_hard = 3072000000
    limit_time_cpu = 120
    limit_time_real = 240
    limit_request = 8192
    log_level = info
