apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.odoo.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: odoo
  ports:
    - name: http
      port: 80
      targetPort: 8069
    - name: websocket
      port: 8072
      targetPort: 8072
