apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ if .Values.odoo.hpa.enabled }}{{ .Values.odoo.hpa.minReplicas }}{{ else }}{{ .Values.odoo.replica }}{{ end }}
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      imagePullSecrets:
        - name: odoo-container
      containers:
        - name: odoo
          image: {{ .Values.odoo.image }}:{{ .Values.odoo.tag }}
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-db-secret
                  key: db_password
          ports:
            - containerPort: 8069
            - containerPort: 8072
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/odoo
            - name: odoo-config
              mountPath: /etc/odoo/odoo.conf
              subPath: odoo.conf
          readinessProbe:
            httpGet:
              path: /web/health
              port: 8069
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /web/health
              port: 8069
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-pvc
            readOnly: false
        - name: odoo-config
          configMap:
            name: odoo-config
            items:
              - key: odoo.conf
                path: odoo.conf
      restartPolicy: Always