apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-replica-config
  namespace: {{ .Release.Namespace }}
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 300
    shared_buffers = 1GB
    effective_cache_size = 3GB
    maintenance_work_mem = 256MB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 3404kB
    huge_pages = off
    min_wal_size = 1GB
    max_wal_size = 4GB