apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-master
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: master
  template:
    metadata:
      labels:
        app: postgres
        role: master
    spec:
      containers:
        - name: postgres
          image: postgres:17
          args: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-db-secret
                  key: db_password
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/pgdata
            - name: postgres-config
              mountPath: /etc/postgresql
              readOnly: true
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user }}
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: postgres-master-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: postgres-master
  updatePolicy:
    updateMode: "Auto"
